website/models.py
"""
This module defines the database models for the Flask web application. These models represent
the User, Device, and Reservation entities in the system, and are used to handle CRUD operations 
and relationships in the database using SQLAlchemy.
"""

from flask_login import UserMixin
from . import database as db

class User(db.Model, UserMixin):
    """
    Represents a user in the system, with details required for authentication and authorization.

    Attributes:
        id (int): The primary key for the user (auto-incremented).
        username (str): The username of the user, must be unique.
        email_address (str): The email address associated with the user.
        password (str): The hashed password for the user's account.
        security_pin (int): A hashed security pin used for additional authentication.
        administrator (bool): A flag indicating if the user has admin privileges.
    """

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(150), unique=True)
    email_address = db.Column(db.String(150))
    password = db.Column(db.String(150))
    security_pin = db.Column(db.Integer)
    administrator = db.Column(db.Boolean)


class Device(db.Model):
    """
    Represents a device in the system, which can be reserved by users.

    Attributes:
        id (int): The primary key for the device (auto-incremented).
        device_brand (str): The brand of the device (e.g., Apple, Samsung).
        device_name (str): The name or model of the device (e.g., iPhone 12).
        device_status (str): The current status of the device (e.g., Active, inactive, maintenance).
        device_type (str): The type of the device (e.g., Laptop, Phone).
        last_use (datetime): The last recorded use of the device.
    """

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    device_brand = db.Column(db.String(150))
    device_name = db.Column(db.String(150))
    device_status = db.Column(db.String(150))
    device_type = db.Column(db.String(150))
    last_use = db.Column(db.DateTime(timezone=True))


class Reservation(db.Model):
    """
    Represents a reservation of a device by a user.

    Attributes:
        id (int): The primary key for the reservation (auto-incremented).
        device_id (int): The ID of the reserved device, references the Device model.
        device_name (str): The name of the reserved device, references the Device model.
        username (str): The username of the user who made the reservation, references the User model.
        start_time (datetime): The start time of the reservation.
        end_time (datetime): The end time of the reservation.
        reason (str): A business reason provided by the user for the reservation.
    """

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    device_id = db.Column(db.Integer, db.ForeignKey("device.id"))
    device_name = db.Column(db.String(150), db.ForeignKey("device.device_name"))
    username = db.Column(db.String(150), db.ForeignKey("user.username"))
    start_time = db.Column(db.DateTime(timezone=True))
    end_time = db.Column(db.DateTime(timezone=True))
    reason = db.Column(db.String(500))

website/__init__.py
from os import path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_apscheduler import APScheduler


database = SQLAlchemy()
mail = Mail()
scheduler = APScheduler()
login_manager = LoginManager()
DATABASE_NAME = "VDMDatabase.db"


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "MYSECRETKEY567"
    """
    app.config["SQLALCHEMY_DATABASE_URI"] = (
        f"sqlite:///{path.join('/database',DATABASE_NAME)}"  
    )"""  # To run this locally change to
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DATABASE_NAME}"
    app.config["MAIL_SERVER"] = "smtp.gmail.com"
    app.config["MAIL_PORT"] = 587  # TLS PORT FOR GMAIL
    app.config["MAIL_USE_TLS"] = True
    app.config["MAIL_USERNAME"] = "devicemanagementprojecttest@gmail.com"
    app.config["MAIL_PASSWORD"] = "QaDummyPassword1"
    app.config["MAIL_DEFAULT_SENDER"] = "devicemanagementprojecttest@gmail.com"
    app.config["SCHEDULER_API_ENABLED"] = True
    scheduler.init_app(app)
    scheduler.start()
    mail.init_app(app)

    database.init_app(app)
    """
    fix emails and scheldues
    fix init py 
    pytest
    lint everything
    try and bypass git commit
    """
    from .models import User
    from .views import views_blueprint
    from .authentication_page_routing import authentication_blueprint
    from .reservation_page_routing import reservation_blueprint
    from .device_page_routing import device_blueprint
    from .user_page_routing import user_blueprint

    app.register_blueprint(views_blueprint, url_prefix="/")
    app.register_blueprint(authentication_blueprint, url_prefix="/")
    app.register_blueprint(device_blueprint, url_prefix="/device")
    app.register_blueprint(reservation_blueprint, url_prefix="/reservation")
    app.register_blueprint(user_blueprint, url_prefix="/user")

    create_database(app)

    login_manager.login_view = "authentication.login_page"
    login_manager.init_app(app)

    # Links login_manager user to the User database
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(id)

    return app


def create_database(app):

    if not path.exists("QaProjectAgile/" + DATABASE_NAME):
        with app.app_context():
            database.create_all()
        print("Created Database!")

website/views.py
"""
This module handles the view-related routes for the web application. It includes a
route for rendering the home page and differentiates between admin and standard users.
"""

from datetime import datetime
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from .models import Reservation

views_blueprint = Blueprint("views", __name__)


@views_blueprint.route("/")
@login_required
def home():
    """
    Renders the home page based on the user's role (admin or standard user).
    """
    user_reservations = Reservation.query.filter_by(
        username=current_user.username
    ).all()

    # Check which reservations are ending within the next hour
    now = datetime.now()
    current_reservations = []
    upcoming_reservations = []
    for reservation in user_reservations:
        if reservation.start_time < now < reservation.end_time:
            current_reservations.append(reservation)
        elif len(upcoming_reservations) < 3:
            upcoming_reservations.append(reservation)
    return render_template(
        "home.html",
        user=current_user,
        upcoming_reservations=upcoming_reservations,
        current_reservations=current_reservations,
    )

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewpoint" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
    <script>
      /*// Listen for the beforeunload event to show the confirmation dialog
      window.onbeforeunload = function (event) {
          // Customize the message that is shown to the user
          event.preventDefault();  // Required by most browsers
          return "Are you sure you want to leave the application? Unsaved changes may be lost.";
      };*/
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-targer="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {%if user.is_authenticated%}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {%else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signup" href="/signup">Sign Up</a>
          {%endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error'%}

    <div class="alert alert-danger alert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% elif category == 'info' %}
    <div class="alert alert-info alert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/confirm_device_delete.html
{% extends "base.html" %} {% block title %}Device delete{% endblock %} {% block
content %}
<h2>Confirm Deletion of Device: {{ device.device_name }}</h2>

<p>This device has the following active reservations:</p>
<ul>
  {% for reservation in reservations %}
  <li>
    {{ reservation.start_time }} - {{ reservation.end_time }} ({{
    reservation.reason }})
  </li>
  {% endfor %}
</ul>

<p>Are you sure you want to delete this device and its active reservations?</p>

<form method="POST" action="{{ url_for('device.confirm_delete') }}">
  <input type="hidden" name="device_id" value="{{ device.id }}" />
  <button type="submit" name="confirm" value="yes">Yes, delete it</button>
  <button type="submit" name="confirm" value="no">No, keep it</button>
</form>
{% endblock %}

website/templates/create_reservation.html
{% extends "base.html" %} {% block title %}Create reservation{% endblock %} {%
block content %}
<form method="GET">
  {%if using_device_id == "True" %}
  <input
    type="hidden"
    name="using_device_id"
    id="using_device_id"
    value="{{using_device_id}}"
  />
  <button type="submit">DeviceId</button>
  {%else%}
  <input
    type="hidden"
    name="using_device_id"
    id="using_device_id"
    value="{{using_device_id}}"
  />
  <button type="submit">Device Name</button>
  {%endif%}
</form>
<form method="POST">
  <h3 align="center">Reserve a device</h3>
  {%if using_device_id == "True"%}
  <div class="form-group">
    <label for="device_id">DeviceId</label>
    <input
      type="number"
      class="form-control"
      id="device_id"
      name="device_id"
      placeholder="Enter the DeviceId of the device you want to reserve"
      required
    />
  </div>
  {%else%}
  <div class="form-group">
    <label for="device_name">Device Name</label>
    <input
      type="text"
      class="form-control"
      id="device_name"
      name="device_name"
      placeholder="Enter the Device name of the device you want to reserve"
      required
    />
  </div>
  {%endif%}

  <div class="form-group">
    <label for="start_time">Start time</label>
    <input
      type="datetime-local"
      class="form-control"
      id="start_time"
      name="start_time"
      placeholder="Enter start time of your reservation"
      required
    />
  </div>
  <div class="form-group">
    <label for="end_time">End time</label>
    <input
      type="datetime-local"
      class="form-control"
      id="end_time"
      name="end_time"
      placeholder="Enter end time of your reservation"
      required
    />
  </div>
  <div class="form-group">
    <label for="reason">Reason</label>
    <input
      type="text"
      class="form-control"
      id="reason"
      name="reason"
      placeholder="Enter Business Reason"
      required
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<a href="{{ url_for('reservation.home') }}">Back to Reservation List</a>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Device Reservation Management{% endblock %}

{% block content %}
<h1>Device Reservation Management</h1>

<a  class="btn btn-primary" id="create_reservation" href="/reservation/create">Create new Reservation</a>
<a  class="btn btn-primary" id="device" href="/device/">See Devices</a>
<a  class="btn btn-primary" id="reservation" href="/reservation">Manage your Reservations</a>
<a  class="btn btn-primary" id="user" href="/user">User Settings</a>

{% if user.administrator %}
<a  class="btn btn-primary" id="user_admin" href="/user/admin">Manage Users</a>
<a  class="btn btn-primary" id="create_device" href="/device/create">Create Device</a>
{% endif %}
<br></br>
<h3>Current Reservations</h3>
{% if current_reservations %}
    <ul>
        {% for reservation in current_reservations %}
            <li>
                <strong>Device:</strong> {{ reservation.device_name }}<br>
                <strong>Start Time:</strong> {{ reservation.start_time }}<br>
                <strong>End Time:</strong> {{ reservation.end_time }}<br>
                <strong>Reason:</strong> {{ reservation.reason }}<br>
            
            </li>
            <hr>
        {% endfor %}
    </ul>
{% else %}
    <p>No current reservations.</p>
{% endif %}
<br></br>
<h3>Upcoming Reservations</h3>
{% if upcoming_reservations %}
    <ul>
        {% for reservation in upcoming_reservations %}
            <li>
                <strong>Device:</strong> {{ reservation.device_name }}<br>
                <strong>Start Time:</strong> {{ reservation.start_time }}<br>
                <strong>End Time:</strong> {{ reservation.end_time }}<br>
                <strong>Reason:</strong> {{ reservation.reason }}<br>
            
            </li>
            <hr>
        {% endfor %}
    </ul>
{% else %}
    <p>No upcoming reservations.</p>
{% endif %}
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter Username"/>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="text" class="form-control" id="password" name="password" placeholder="Enter Password"/>
    </div>
    <div class="form-group">
        <label for="pin">Security Pin</label>
        <input type="number" class="form-control" id="pin" name="pin" placeholder="Enter Security Pin"/>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/read_device.html
{% extends "base.html" %} {% block title %}All Devices{% endblock %} {% block
content %}
<body>
  <h1>Device List</h1>
  <table border="1">
    <thead>
      <tr>
        <th>Device ID</th>
        <th>Device Brand</th>
        <th>Device Name</th>
        <th>Device Status</th>
        <th>Device Type</th>
        <th>Last Use</th>
        <th>Actions</th>
        <!-- New column for action buttons -->
      </tr>
    </thead>
    <tbody>
      {% for device in devices %}
      <tr>
        <td>{{ device.id }}</td>
        <td>{{ device.device_brand }}</td>
        <td>{{ device.device_name }}</td>
        <td>{{ device.device_status }}</td>
        <td>{{ device.device_type }}</td>
        <td>{{ device.last_use }}</td>
        <td>
          <!-- Buttons for actions -->
          <!-- View Availability -->
          <form
            method="GET"
            action="{{ url_for('device.see_availability') }}"
            style="display: inline"
          >
            <input type="hidden" name="device_id" value="{{ device.id }}" />
            <button type="submit">View Availability</button>
          </form>
          {% if user.administrator %}
          <!-- Update Device -->
          <form
            method="GET"
            action="{{ url_for('device.update') }}"
            style="display: inline"
          >
            <input type="hidden" name="device_id" value="{{ device.id }}" />
            <button type="submit">Update</button>
          </form>

          <!-- Delete Device (using POST to simulate DELETE) -->
          <form
            method="POST"
            action="{{ url_for('device.home') }}"
            style="display: inline"
          >
            <input type="hidden" name="_method" value="DELETE" />
            <!-- Simulating DELETE method -->
            <input type="hidden" name="device_id" value="{{ device.id }}" />
            <button
              type="submit"
              onclick="return confirm('Are you sure you want to delete this device?');"
            >
              Delete
            </button>
          </form>
          {%endif%}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <!-- Button to create a new device -->
  {% if user.administrator %}
  <br />
  <form method="GET" action="{{ url_for('device.create') }}">
    <button type="submit">Create New Device</button>
  </form>
  {% endif %}
</body>
{% endblock %}

website/templates/read_reservation.html
{% extends "base.html" %} {% block title %}All Reservations{% endblock %} {%
block content %}
<body>
  <h1>Reservation List</h1>

  <!-- Toggle button for admin to switch between all reservations and their own -->
  {% if current_user.administrator %}
  <form method="GET" action="{{ url_for('reservation.home') }}">
    <input
      type="hidden"
      name="show_all"
      value="{{ 'false' if show_all else 'true' }}"
    />
    <button type="submit">
      {% if show_all %} Show Only My Reservations {% else %} Show All Users'
      Reservations {% endif %}
    </button>
  </form>
  {% endif %}

  <table border="1">
    <thead>
      <tr>
        <th>Reservation ID</th>
        <th>Device ID</th>
        <th>Device Name</th>
        <th>Username</th>
        <th>Start Time</tåh>
        <th>End Time</th>
        <th>Reason</th>
        <th>Actions</th>
        <!-- New column for action buttons -->
      </tr>
    </thead>
    <tbody>
      {% for reservation in reservations %}
      <tr>
        <td>{{ reservation.id }}</td>
        <td>{{ reservation.device_id }}</td>
        <td>{{ reservation.device_name }}</td>
        <td>{{ reservation.username }}</td>
        <td>{{ reservation.start_time }}</td>
        <td>{{ reservation.end_time }}</td>
        <td>{{ reservation.reason }}</td>
        <td>
          <!-- Modify Button -->
          <form
            method="GET"
            action="{{ url_for("reservation.update", reservation_id=reservation.id) }}"
            style="display: inline"
          >
            <input
              type="hidden"
              name="reservation_id"
              value="{{ reservation.id }}"
            />
            <button type="submit">Update</button>
          </form>
          <!-- Delete Button (with confirmation) -->
          <form
            method="POST"
            action="{{ url_for('reservation.home') }}"
            style="display: inline"
          >
            <input type="hidden" name="_method" value="DELETE" />
            <input
              type="hidden"
              name="reservation_id"
              value="{{ reservation.id }}"
            />
            <button
              type="submit"
              onclick="return confirm('Are you sure you want to delete this reservation?');"
            >
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <!-- Button to create a new reservation -->
  <br />
  <form method="GET" action="{{ url_for('reservation.create') }}">
    <button type="submit">Create New Reservation</button>
  </form>
</body>
{% endblock %}

website/templates/read_user.html
{% extends "base.html" %} {% block title %}All Users{% endblock %} {% block
content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='css/style.css') }}"
/>
<body>
  <h1>See All Users</h1>
  <table border="1">
    <thead>
      <tr>
        <th>User ID</th>
        <th>Username</th>
        <th>Email Address</th>
        <th>Administrator</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.email_address }}</td>
        <td>{{ user.administrator }}</td>
        <td>
          <div id="form-{{ user.id }}" class="action-form">
            <form
              method="POST"
              action="{{ url_for('user.admin_view') }}"
              onsubmit="return confirm('Are you sure you want to make {{user.username}} admin "
            >
              <input type="hidden" name="user_id" value="{{ user.id }}" />
              <button type="submit" name="admin" value="admin">
                Make Admin
              </button>
            </form>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>
{% endblock %}

website/templates/see_device_availability.html
{% extends "base.html" %} {% block title %}Device Availability{% endblock %} {%
block content %}
<h2>Device Availability: {{ device.device_name }}</h2>

<h3>Reservations:</h3>
<table border="1">
  <thead>
    <tr>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    {% for reservation in reservations %}
    <tr>
      <td>{{ reservation.start_time }}</td>
      <td>{{ reservation.end_time }}</td>
      <td>{{ reservation.reason }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<h3>Available Time Slots:</h3>
<table border="1">
  <thead>
    <tr>
      <th>Available From</th>
      <th>Available Until</th>
    </tr>
  </thead>
  <tbody>
    {% for slot in availability_slots %}
    <tr>
      <td>{{ slot.start }}</td>
      <td>
        {% if slot.end %} {{ slot.end }} {% else %} Indefinitely {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{{ url_for('device.home') }}">Back to Device List</a>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="username">Username</label>
    <input
      type="text"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter Username"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="text"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter Password"
    />
  </div>
  <div class="form-group">
    <label for="pin">Security Pin</label>
    <input
      type="number"
      class="form-control"
      id="pin"
      name="pin"
      placeholder="Enter Security Pin"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/update_device.html
{% extends "base.html" %} {% block title %}Update Devices{% endblock %} {% block
content %}
<form
  method="POST"
  action="{{ url_for('device.update', device=device) }}"
>
  <br />
  <label for="device_name">Device Name:</label>
  <input
    type="text"
    id="device_name"
    name="device_name"
    value="{{ device.device_name }}"
  />
  <br />

  <label for="device_brand">Device Brand:</label>
  <input
    type="text"
    id="device_brand"
    name="device_brand"
    value="{{ device.device_brand }}"
  />
  <br />

  <label for="device_status">Device Status:</label>
  <select name="device_status" id="device_status">
    <option>{{ device.device_status }}</option>
    <option value="Active">Active</option>
    <option value="Inactive">Inactive</option>
    <option value="Maintenance">Maintenance</option>
  </select>
  <br />

  <label for="device_type">Device Type:</label>
  <input
    type="text"
    id="device_type"
    name="device_type"
    value="{{ device.device_type }}"
  />
  <br />

  <label for="last_use">Last Use:</label>
  <input
    type="datetime-local"
    id="last_use"
    name="last_use"
    value="{{ device.last_use }}"
  />
  <br />

  <button type="submit">Update Device</button>
</form>
<a href="{{ url_for('device.home') }}">Back to Device List</a>
{% endblock %}

website/templates/update_reservation.html
{% extends "base.html" %} {% block title %}Update Reservation{% endblock %} {%
block content %}
<form
  method="POST"
  action="{{ url_for("reservation.update", reservation_id=reservation.id) }}"
>
  <br />

  <label for="device_id">Device ID:</label>
  <input
    type="text"
    id="device_id"
    name="device_id"
    value="{{ reservation.device_id }}"
  />
  <br />

  <label for="start_time">Start Time:</label>
  <input
    type="datetime-local"
    id="start_time"
    name="start_time"
    value="{{ reservation.start_time }}"
  />
  <br />

  <label for="end_time">End Time:</label>
  <input
    type="datetime-local"
    id="end_time"
    name="end_time"
    value="{{ reservation.end_time }}"
  />
  <br />

  <label for="reason">Reason:</label>
  <textarea id="reason" name="reason" rows="4" cols="50">
{{ reservation.reason }}</textarea
  >
  <br />

  <button type="submit">Update Reservation</button>
</form>

<a href="{{ url_for('reservation.home') }}">Back to Reservation List</a>
{% endblock %}

website/templates/user_settings.html
{% extends "base.html" %} {% block title %}User Settings{% endblock %} {% block
content %}
<h1>User Settings</h1>

<!-- Display user information -->
<div class="user-info">
  <p><strong>Username:</strong> {{ user.username }}</p>
  <p><strong>Email Address:</strong> {{ user.email_address }}</p>
  <p><strong>User ID:</strong> {{ user.id }}</p>
  <p>
    <strong>Administrator:</strong> {{ 'Yes' if user.administrator else 'No' }}
  </p>
</div>

<!-- Buttons to delete the account or update user details -->
<div class="user-actions">
  <form
    method="POST"
    action="{{ url_for('user.delete_account') }}"
    onsubmit="return confirm('Are you sure you want to delete your account? This action is irreversible.');"
  >
    <button type="submit" class="btn btn-danger">Delete Account</button>
    <input type="hidden" name="_method" value="DELETE" />
  </form>

  <br />

  <form method="GET" action="{{ url_for('user.change_details') }}">
    <button type="submit" class="btn btn-primary">Update Details</button>
  </form>
</div>

<a href="{{ url_for('views.home') }}">Back to Home</a>
{% endblock %}

website/templates/user_settings_reauthenticate.html
{% extends "base.html" %} {% block title %}User Settings{% endblock %} {% block
content %}
<h1>User Settings</h1>

<form method="POST" action="{{ url_for('user.reauthenticate') }}">
  <h3>Re-authentication</h3>
  <label for="password"> Password:</label>
  <input type="password" id="password" name="password" required />
  <br />
  <label for="pin"> Security Pin:</label>
  <input type="number" id="pin" name="pin" required />
  <br />

  <button type="submit">Submit</button>
</form>

<a href="{{ url_for('views.home') }}">Back to Home</a>
{% endblock %}